### PR TITLE
Add custom header support for JWS

### PR DESCRIPTION
**Pull request by theikkila**
Fixes issues #46 and #44

### CODE REVIEW

**Comment by dpsutton** [comment]
Is there any plan to merge this? I'm using Firebase for authentication and jwt. Their header includes the alg as well as a key id for the public key for the signature. 

```
{
  "alg": "RS256",
  "kid": "48b0f8082a7be2db150268ac6b5cc82a29bedd08"
}
```

which identies which of the public keys at https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com was used to sign the jwt. However, the custom key is not recoverable until this patch goes in.

**Comment by niwinz** [comment]
yeah, i this will be merged monday probably.

On Aug 18, 2017 9:20 PM, "dpsutton" <notifications@github.com> wrote:

Is there any plan to merge this? I'm using Firebase for authentication and
jwt. Their header includes the alg as well as a key id for the public key
for the signature.

{
  "alg": "RS256",
  "kid": "48b0f8082a7be2db150268ac6b5cc82a29bedd08"
}

which identies which of the public keys at https://www.googleapis.com/
robot/v1/metadata/x509/securetoken@system.gserviceaccount.com was used to
sign the jwt. However, the custom key is not recoverable until this patch
goes in.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/funcool/buddy-sign/pull/52#issuecomment-323439435>, or mute
the thread

**Comment by dpsutton** [comment]
ping :)

**Comment by niwinz** [comment]
my apologies, i remember about this pr, but i'm too busy this week :( ( i
have a lot of pending stuff, i'll try to merge and release ASAP)

**Comment by dpsutton** [comment]
@niwinz thanks for the update. i appreciate your care in not just merging without verifying for yourself. take your time :+1:

**Comment by niwinz** [comment]
nice job! thanks!

**Comment by niwinz** [comment]
@dpsutton merged and 2.1.0 released. I will update the main buddy metapackage when I trully know that everything is working as expected. Please, can you check the latest release and give me some feedback :D

**Comment by dpsutton** [comment]
Thanks! I'll bump it and check. Really appreciate your help

**Comment by dpsutton** [comment]
@niwinz I'm using 2.2.0 for both suppressing claims checking in testing and inspecting custom headers from the token. Feeling good to me.

**Comment by niwinz** [comment]
Thanks!

**Comment by theikkila** [comment]
Good work guys! Thanks!

**Pull request merged**
