### PR TITLE
A fix for #22

### PR DESCRIPTION
**Pull request by FreekPaans**
I've taken a stab at #22, let me know if I need to improve anything. If this is the right direction I can do a similar solution for JWE JWTs.

### CODE REVIEW

**Comment by niwinz** [comment]
At quick review it looks very very nice! Thanks for your time. I'll try to take some time this afternoon for deeper review.

JWE definitively should go in the same direction ;)

**Comment by niwinz** [comment]
I close this in favor of #24 that already includes this work.

**Comment by FreekPaans** [comment]
Am currently on vacaction, will be able to have a look (and do jwe impl)
next week.

**Comment by niwinz** [comment]
Don't worry and have a nice holiday, this stuff is already done and 1.0.0 version is released ;)

**Pull request closed without merging**
