### PR TITLE
Added JWK loading and exporting support

### PR DESCRIPTION
**Pull request by shilder**
1. Converting from JWK to JCA keys
2. Converting from JCA keys to JWK representation

- RSA keys
- EC keys
- OKP + EdDSA keys

Added tests with examples from RFCs for all key types

### CODE REVIEW

**Comment by shilder** [comment]
Some notes

1. It requires latest buddy-core (for eddsa provider) - need version bump
2. Don't know if i made license and copyright notices right
3. Almost no documentation for now

So it's more like work in progress and request for discussion :)

**Comment by niwinz** [comment]
Very nice work @shilder ! I have taken a look into the code and it looks very clean and well written, so i'm ok for merging it. Do yo consider adding docs and the missing stuff in an other PR or you prefer adding that here on this PR? I can merge this PR right now also if you prefer and the missing stuff can come later.

I'm currently on my holidays, so I can't bump the versions right now. But as soon as I can do it, i will make more exahustive review and will bump the version with this awesome feature, thanks!

**Comment by shilder** [comment]
Sorry, was very busy, i'll try to write some documentation in this PR

**Comment by niwinz** [comment]
That will be awesome, because i want to release a new version with this of all the buddy packages :D

**Comment by shilder** [comment]
I was working on this PR and one particular thought occurred to me - i don't think `buddy-sign` is the right place for this functionality, semantically it should be somewhere in `buddy.core.keys`. But `buddy-core` has no JSON parsing library - that's why this JWK thing landed in `buddy-sign` in the first place.

Now i'm thinking that maybe it's better to move JWK keys to `buddy-core` or even separate library, i don't know.  It will also be great if buddy can support loading (and even saving) keys from PEM, DER and JWK formats, and maybe we can add key generation facilities someday.

It will be harder to move this functionality to another package after new version is released.

**Comment by niwinz** [comment]
I think you are right! In fact, i think that buddy-sign name is already not good for this package, because it not only signs. An possible idea of the package changes can be:

- buddy: buddy-core + buddy-sign + the keys functionality
- buddy-auth: the actual buddy-auth
- buddy-hashers: the actual password hashers

What do you think about that change?

**Comment by shilder** [comment]
Well, package changes are breaking ones, i prefer to avoid breaking changes.

We can leave artifacts as is and move jwk code to `buddy-core`, `cheshire` could be `provided` with note in documentation that you need to manually include it in dependencies if you want to read JWK keys (not everyone need it). 

Or it could be opposite - `cheshire` will be included by default with advice to use `exclusions` mechanism to remove unnecessary JSON parsing libraries (which is annoing to have alongside basic crypto functions)

`buddy-sign` is actually more `buddy-jwt` or `buddy-jose` and i don't think it's good idea to include JWT in `buddy-core`

**Comment by niwinz** [comment]
Ok, lets do it, including cheshire with note in doc about possible exclude it.

**Comment by niwinz** [comment]
I go to merge it and then, move into buddy-core ;)

**Comment by niwinz** [comment]
Already on master on buddy-core with minimal changes. I will port the documentation part and then, remove the repeated code from this repository.

**Comment by shilder** [comment]
Thanks, i got sick and can't work right now :(

**Pull request merged**
