### PR TITLE
Added test for claims validation when using a JWE JWT

### PR DESCRIPTION
**Pull request by FreekPaans**

### CODE REVIEW

**Comment by niwinz** [comment]
Thanks! I'll review it this afternoon :D

**Comment by niwinz** [comment]
Test seems like raises a timeout on travis environment, they passes all ok on local. Thank!

**Comment by FreekPaans** [comment]
Travis builds have been broken for a while now, right? Maybe different
issue?

**Comment by niwinz** [comment]
Seems like a big iteration number for test.check makes it timeout or something similar. I'll research it.

**Pull request merged**
